name: hello-world
on: push

jobs:
  hello-world-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
  
